services:
  # server:
  #   build:
  #     context: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - MONGO_URI=mongodb://db:27017/internship
  db:
    image: mongo:latest
    container_name: mongo
    volumes:
      - test-internship:/data/db
    ports:
      - "27017:27017"

volumes:
  test-internship:
